---
layout:     post
title:      B站 视频投稿
date:       2020-10-16
author:     Tangle
catalog: true
tags:
    - bilibili
---

0. bilibili_video_uploader：<https://gitee.com/nbodyfun/bilibili_video_uploader>
0. bilibili_video_uploader：<https://gitee.com/tangle5500/bilibili_video_uploader>
0. bilibili-live-tools：<https://github.com/Dawnnnnnn/bilibili-live-tools.git>
0. bilibili-live-tools：<https://gitee.com/tangle5500/bilibili-live-tools>

# 修改

## bilibili-live-tools

```
conf
    bilibili.conf
    user.conf
bilibili.py
configloader.py
login.py
printer.py
run.py
```

```
# run.py

import asyncio
from login import login

loop = asyncio.get_event_loop()
tasks1 = [
    login().login_new()
]
loop.run_until_complete(asyncio.wait(tasks1))
```

```
# login.py

t=open(r"conf\cookie.txt","w")                 # 加代码
t.write(str(dic_saved_session["cookie"]))      # 加代码
t.close                                        # 加代码
Printer().printer(f"登录成功", "Info", "green") # 源代码
```

## bilibili_video_uploader

```
# bilibili_up.py
try:                                                                          # 加代码
    res1 = self.preupload(filename=filename, filesize=filesize)               # 源代码
except:                                                                       # 加代码
    import os,subprocess                                                      # 加代码
    subprocess.call(f"cd ../bilibili-live-tools & python run.py", shell=True) # 加代码
```

# 例子

```
-sd [SESSDATA] # SESSDATA
-bj [bili_jct] # bili_jct
-s [SOURCE]    # 来源声明
-t [TITLE]     # 标题
[video_path]   # 视频文件
```

```
python bilibili_up.py -sd [SESSDATA] -bj [bili_jct] -t [TITLE] -s [SOURCE] [video_path]
```

# ERROR

##  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
SESSDATA
bili_jct
```

```
Traceback (most recent call last):
  File "D:\Python\bilibili\bilibili_video_uploader\bilibili_up.py", line 397, in <module>
    script_main()
  File "D:\Python\bilibili\bilibili_video_uploader\bilibili_up.py", line 393, in script_main
    ).publish_video(args.video_path, atitle=args.title, adesc=args.desc, acopyright=args.copyright, asource=args.source, specified_type=args.typeid, specified_tags=args.tags)
  File "D:\Python\bilibili\bilibili_video_uploader\bilibili_up.py", line 84, in publish_video
    res1 = self.preupload(filename=filename, filesize=filesize)
  File "D:\Python\bilibili\bilibili_video_uploader\bilibili_up.py", line 274, in preupload
    headers={'TE': 'Trailers'}
  File "D:\Tangle\Python 3.6.5\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Tangle\Python 3.6.5\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Tangle\Python 3.6.5\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Tangle\Python 3.6.5\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```
Traceback (most recent call last):
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 677, in urlopen
    chunked=chunked,
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 1331, in getresp
onse
    response.begin()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 266, in _read_st
atus
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\requests\adapters.py", l
ine 449, in send
    timeout=timeout
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\util\retry.py",
line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\packages\six.py"
, line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 677, in urlopen
    chunked=chunked,
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\urllib3\connectionpool.p
y", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 1331, in getresp
onse
    response.begin()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\http\client.py", line 266, in _read_st
atus
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Re
mote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\IFIX\IFIX\A_server\bilibili\bilibili_video_uploader\bilibili_up.py",
line 411, in <module>
    script_main()
  File "D:\IFIX\IFIX\A_server\bilibili\bilibili_video_uploader\bilibili_up.py",
line 407, in script_main
    ).publish_video(args.video_path, atitle=args.title, adesc=args.desc, acopyri
ght=args.copyright, asource=args.source, specified_type=args.typeid, specified_t
ags=args.tags)
  File "D:\IFIX\IFIX\A_server\bilibili\bilibili_video_uploader\bilibili_up.py",
line 133, in publish_video
    title=filestem, bfilestem=bfilestem, desc=adesc)[0]
  File "D:\IFIX\IFIX\A_server\bilibili\bilibili_video_uploader\bilibili_up.py",
line 234, in choose_type
    'TE': 'Trailers'}).json()
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\requests\sessions.py", l
ine 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\requests\sessions.py", l
ine 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\requests\sessions.py", l
ine 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\IFIX\IFIX\python_3.6.5_x86\lib\site-packages\requests\adapters.py", l
ine 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected(
'Remote end closed connection without response',))
```
